language: node_js
node_js:
  - "0.10.30"
before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
script:
  - grunt default
after_success:
  - git add build/
  - git commit -m "Build output"
  - git push origin master